wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1632629675
    t:
      3:
      - 2
      - 16
      4: 3.8.11
      5: 0.12.2
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
learning_rate:
  desc: null
  value: 0.02
